---
layout: default
author: "Kajal"
date: "23/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  **PROFILE**
 
+	OVER 20 YEARS INTERNATIONAL TELECOMS EXPERIENCE, WORKING WITH TIER 1 INDUSTRY LEADERS.
+	DETAILED KNOWLEDGE OF BSS SYSTEM CUSTOMER JOURNEY 
+	PROVEN TEAM LEADERSHIP EXPERIENCE IN ARCHITECTING SUCCESSFUL PROJECTS
+	EXCELLENT COMMUNICATION AND INTERPERSONAL SKILLS AT ALL LEVELS
+	ABILITY TO RAPIDLY LEARN BUSINESS CAPABILITIES OF PRODUCTS AND APPLICATIONS. 
+	CAN WORK POSITIVELY IN A CROSS-FUNCTIONAL  CUSTOMER AND VENDOR TEAM ENVIRONMENT. 
+	PROVEN ABILITY TO DELIVER IN BOTH ON-SITE AND REMOTE ACCESS SITUATIONS.

##  **AREAS OF EXPERTISE**
 
+	Design and Delivery of Key Business Transformation Consulting Practice Services
+	Business Readiness – Design and Delivery of sellable services to support the customer in identifying operational business impacts of target state solution and ensuring readiness activities are owned and implemented. A critical feed into go/no-go assessment criteria to ensure impacted business stakeholders are ready to transition to the new landscape.
+	Business Process Management & Optimization– Design and delivery of a blueprint methodology and accompanying library of re-usable e-TOM compliant processes aligned to the full BSS suite of applications. The blueprint approach significantly reduced timelines for key waterfall and agile design and testing phases. Analysing Business processes and identifying process improvement opportunities.
+	Business Process driven sandbox development – using business process to plan sandbox roadmap and facilitate expedited development cycles. 
+	Business Deployment – Designing services to support the customer during Production Deployment rollout including Business Continuity Planning, defining detailed execution plans that incorporate migration activities. Set up and execution of deployment control functions to ensure an effective and structured deployment experience. Post deployment stabilization support
+	Business parameters/configuration –Data capture & Implementation support to configure the business capabilities on BSS products
+   End to end process focused requirements management quality assurance.
+   Statement of work quality assurance
+	Subject matter expert for CRM, Billing, Inventory & Ordering products at all phases of the project lifecycle

